# Generated by Django 4.2.2 on 2023-07-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotidb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="solved_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="solved_puzzles",
        ),
    ]
