DROP TABLE IF EXISTS PlaylistTrack;
DROP TABLE IF EXISTS Playlist;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS ArtistGenre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Artist;